config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'works/new'
  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  get 'lists/index'
  get 'rooms/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  
  resources :users
  resources :rooms do
      member do
        get "buy"
        post "pay"
    end
  end
  resources :messages
  resources :works do
    get 'works', to: 'works#search'
  end
  resources :password_resets, only: %i[new create edit update]
  
  namespace :admin do
    resources :users, only: [:index]
  end
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :costs, only: %i[new create]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
# def  has_unread_messages
#   #current_userのメッセージがある場合
#   unless self.rooms.room_ids.messages
# end  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])[a-z,A-Z,\d]{8,20}\z/
  
# 　allow_blankはエラーメッセージ用
  validates :name, 
            presence: true, length: {in: 1..15, allow_blank: true}
  validates :email,
            uniqueness: true, presence: true, format: {with: VALID_EMAIL_REGEX, allow_blank: true}
  validates :password, :password_confirmation, 
            presence: true, on: :create
  validates :password, :password_confirmation, 
            presence: true, on: :update, allow_blank: true, 
            format: {with: VALID_PASSWORD_REGEX, allow_blank: true}
  validates :password, confirmation: true
  validates :artist, presence: true
  validates :prefectures, presence: true
  # validates :profile_image, allow_blank: true
  validates :profile, length: {maximum: 200}, allow_blank: true
  validates :reset_password_token, allow_nil: true, uniqueness: true
  
  has_many :works, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :costs, dependent: :destroy
  has_one :card, dependent: :destroy
  
  mount_uploader :profile_image, ImageUploader
  
  enum artist: {yes: 1, no: 2}
  enum prefectures: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20, 岐阜県: 21, 静岡県: 22, 愛知県: 23,
    三重県: 24, 滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :admin_user
    
    def index
       @users = User.all.order(:id)
    end
    
    def show
        
    end
    
    private
    def admin_user
        redirect_to (root_path) unless current_user.admin? 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create, :show]
  before_action :set_user, only: %i[edit update destroy]
  
  def index
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: '登録が完了しました'
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    # 自分が参加しているメッセージルームの情報を取得する
    @currentUserEntry = Entry.where(user_id: current_user.id)
    # 選択したユーザーのメッセージルームの情報を取得する
    @userEntry = Entry.where(user_id: @user.id)
    
    # current_userと選択したユーザー間に共通のメッセージルームがあれば、フラグを立てる
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      # 無ければ作成する
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
      
    # 自分の作品一覧
    @user_name = current_user.name
    @works = @user.works
  end
  
  def edit
      @uer = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(edit_user_params)
      redirect_to user_path(current_user.id), success: 'プロフィールを更新しました'
    else
      render :edit
    end
  end
  
  private
  def set_user
    @user = User.find(current_user.id)
  end
  
  def user_params
    params.require(:user).permit(:name, :prefectures, :email, :password, :password_confirmation, :artist, :profile_image, :profile_image_cache, :profile)
  end
  
  def edit_user_params
    params.require(:user).permit(:name, :prefectures, :email, :artist, :profile_image, :profile)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = user-edit-wrapper>
    <div class = "container">
        <div class = "row">
            <div class = "col-md-offset-3 col-md-6">
                
                <% if @user.errors.any? %>
                    <div class = "alert alert-danger">
                        <ul>
                            <% @user.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
                
                <h1 class = "heading">プロフィール編集</h1>
                <%= form_with model: @user, local: true do |f| %>
                    <div class = "form-group">
                        <%= f.label :name, '名前' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :prefectures, '都道府県' %>
                        <%= f.select :prefectures, User.prefectures.keys, {}, class: 'select-form' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :email, 'メールアドレス' %>
                        <%= f.email_field :email, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :artist, '作品を投稿しますか' %>
                        <div class = "radio-inline">
                            <%= f.radio_button :artist, :yes %>
                            <%= f.label :artist, 'はい', class: 'radio-label' %>
                        </div>
                        <div class = "radio-inline">
                            <%= f.radio_button :artist, :no %>
                            <%= f.label :artist, 'いいえ', class: 'radio-label' %>
                        </div>
                    </div>
                     <div class = "form-group">
                        <%= f.label :profile_image, 'プロフィール画像(任意)' %>
                        <div class = "profile-image-field">
                            <% if @user.profile_image.present? %>
                                <%= image_tag @user.profile_image.url, id: 'img_prev', class: 'profile-image' %>
                            <% else %>
                                <%= image_tag 'icons/マイページ.png', id: 'img_prev', class: 'profile-image' %>
                            <% end %>
                        </div>
                        <%= f.file_field :profile_image, id: 'user_img' %>
                        
                        <script type="text/javascript">
                          $(function() {
                            function readURL(input) {
                                if (input.files && input.files[0]) {
                                var reader = new FileReader();
                                reader.onload = function (e) {
                                    $('#img_prev').attr('src', e.target.result);
                                    }
                                reader.readAsDataURL(input.files[0]);
                                }
                            }
                            $("#user_img").change(function(){
                                readURL(this);
                            });
                          });
                        </script>
                    </div>
                    <div class = "form-group">
                        <%= f.label :profile, 'プロフィール(任意)' %>
                        <%= f.text_area :profile, class: 'form-control' %>
                    </div>
                    
                    <%= f.submit '更新', class: 'btn btn-outline-secondary btn-black' %>
                <% end %>
                <p class = "edit-password-btn">
                    <%= link_to 'パスワードを変更する方はこちら', password_resets_new_path  %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class = "user-new-wrapper">
    <div class = "container">
        <div class = "row">
            <div class ="col-md-offset-3 col-md-6 user-new-container">
                <% if @user.errors.any? %>
                    <div class = "alert alert-danger">
                        <ul>
                            <% @user.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
                <h1 class = "heading">新規登録</h1>
                <hr class = "hr-color" style = "margin-bottom: 35px;">
                <%= form_with model: @user, local: true do |f| %>
                    <div class = "form-group">
                        <%= f.label :name, '名前' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :prefectures, '都道府県' %>
                        <%= f.select :prefectures, User.prefectures.keys, {}, class: 'select-form' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :email, 'メールアドレス' %>
                        <%= f.email_field :email, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :password, 'パスワード', class: 'text-black' %>
                        <br><%= f.label '(アルファベット大文字、小文字、数字を1つ以上含む、8文字以上20文字以下)', class: 'text-small' %>
                        <%= f.password_field :password, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label :password_confirmation, 'パスワード確認' %>
                        <%= f.password_field :password_confirmation, class: 'form-control' %>
                    </div>
                    <div class = "form-group">
                        <%= f.label '作品を投稿しますか', for: "constraction" %>
                        <div class = "radio-inline">
                            <%= f.radio_button :artist, :yes %>
                            <%= f.label :artist, 'はい' %>
                        </div>
                        <div class = "radio-inline">
                            <%= f.radio_button :artist, :no %>
                            <%= f.label :artist, 'いいえ' %>
                        </div>
                    </div>
                    <div class = "form-group">
                        <%= f.label :profile_image, 'プロフィール画像(任意)' %><br>
                        <div class = "profile-image-field">
                            <% if @user.profile_image.present? %>
                                <%= image_tag @user.profile_image, id: 'img_prev', class: 'profile-image' %>
                            <% else %>
                                <%= image_tag 'icons/マイページ.png', id: 'img_prev', class: 'profile-image' %>
                            <% end %>
                        </div>
                        <%= f.file_field :profile_image, id: 'user_img' %>
                        
                        <script type="text/javascript">
                          $(function() {
                            function readURL(input) {
                                if (input.files && input.files[0]) {
                                var reader = new FileReader();
                                reader.onload = function (e) {
                                    $('#img_prev').attr('src', e.target.result);
                                    }
                                reader.readAsDataURL(input.files[0]);
                                }
                            }
                            $("#user_img").change(function(){
                                readURL(this);
                            });
                          });
                        </script>
                    </div>
                    <div class = "form-group">
                        <%= f.label :profile, 'プロフィール(任意)' %>
                        <%= f.text_area :profile, class: 'form-control' %>
                    </div>
                    <%= f.submit "登録", class: 'btn btn-outline-secondary btn-black' %>
                <% end %>
                
                <%= link_to 'トップページ', root_path %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class = "user-show-wrapper">
    <div class = "container">
        <div class = "my-page">
            <% if @user.artist == "yes" %>
                <h1 class = "text-center text-black"><%= @user.name %>さんのページ</h1>
                <div class = "user-show-message">
                <% unless @user.id == current_user.id %>
                    <!--メッセージRoomが既にある場合はそこへのリンク(showアクション)-->
                    <% if @isRoom == true %>
                        <%= link_to "メッセージを送る", room_path(@roomId), class: "btn btn-default btn-lg"%>
                    <% else %>
                        <%= form_with model:@room, local: true do |f| %>
                            <%= fields_for @entry do |e| %>
                                <%= e.hidden_field :user_id, :value=> @user.id %>
                            <% end %>
                            <%= f.submit "メッセージを始める", class: 'btn btn-default btn-lg' %>
                        <% end %>
                    <% end %>
                <% end %>
                </div>
                
                <div class = "user-show-profile-box">
                        <div class = "user-show-profile-image-box">
                            <% if @user.profile_image? %>
                                <%= image_tag @user.profile_image.url, class: 'user-show-profile-image' %>
                            <% else %>
                                <%= image_tag 'icons/マイページ.png', class: 'user-show-profile-image' %>
                            <% end %>
                        </div>
                        <div class = "user-show-profile-sentence-box">
                            <% if @user.profile? %>
                                <%= safe_join(@user.profile.split("\n"),tag(:br)) %>
                            <% else %>
                                <h4>プロフィール文はありません</h4>
                            <% end %>
                        </div>
                    </div>
                    <% if @user.id == current_user.id %>
                        <div class = "user-show-profile-footer">
                            <%= link_to '編集', edit_user_path %>
                        </div>
                    <% end %>
                
                <div class = "list">
                    <span class = "type-title">
                       <目的> 
                    </span><br>
                    <%= form_with url: works_path, method: :get, local: true do |form| %>
                        <%= form.select("type_id", Type.pluck(:work_type, :id), {include_blank: true}) %>
                        <%= form.submit '検索', name: nil %>
                    <% end %>
                </div>
                <% if @works.blank? %>
                    <h3 class = "text-center">作品が投稿されていません</h3>
                <% else %>
                    <div class = "row">
                    <% @works.each do |work| %>
                        <div class = "col-xs-4 col-md-3">
                            <%= link_to work_path(work.id) do %>
                                <div class = "work-index-three">
                                    <div class = "work-image">
                                        <%= image_tag work.image.url%>
                                    </div>
                                    <span class = "work-title">
                                        <%= truncate(work.title, length: 15) %>
                                    </span><br>
                                    <span class = "work-text">
                                        <%= truncate(work.description, length: 17) %>
                                    </span><br>
                                    <span class = "artist">
                                        <%= work.user.name %>
                                    </span><br>
                                    <span>
                                        <% work.types.each  do |type| %>
                                        <%= type.work_type %>
                                        <% end %>
                                    </span>
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
                <% end %>
            <% else %>
                <h1 class = "text-center text-black"><%= @user.name %>さんのページ</h1>
                <div class = "user-show-profile-box">
                        <div class = "user-show-profile-image-box">
                            <% if @user.profile_image? %>
                                <%= image_tag @user.profile_image.url, class: 'user-show-profile-image' %>
                            <% else %>
                                <%= image_tag 'icons/マイページ.png', class: 'user-show-profile-image' %>
                            <% end %>
                        </div>
                        <div class = "user-show-profile-sentence-box">
                            <% if @user.profile? %>
                                <%= safe_join(@user.profile.split("\n"),tag(:br)) %>
                            <% else %>
                                <h4>プロフィール文はありません</h4>
                            <% end %>
                        </div>
                    </div>
                    <% if @user.id == current_user.id %>
                        <div class = "user-show-profile-footer">
                            <%= link_to '編集', edit_user_path %>
                        </div>
                    <% end %>
                    <h3 class = "text-center">作品投稿者ではありません</h3>
            <% end %>
            <%= link_to 'トップページ', root_path %>
            <% if current_user.admin == true %>
                <%= link_to '管理者画面', admin_users_path %>
            <% end %>
        </div>
    </div>
</div>