config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'works/new'
  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  get 'lists/index'
  get 'rooms/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  
  resources :users
  resources :rooms do
      member do
        get "buy"
        post "pay"
    end
  end
  resources :messages
  resources :works do
    get 'works', to: 'works#search'
  end
  resources :password_resets, only: %i[new create edit update]
  
  namespace :admin do
    resources :users, only: [:index]
  end
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :costs, only: %i[new create]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :require_login
    require 'payjp'
    
    def new
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      @card = Card.where(user_id: current_user.id)
    end
    
    # def create
    #   Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    #   unless params['payjp_token'].blank?
    #     #   生成したトークンから、顧客情報と紐付け、PAY.JP管理サイトに登録
    #       customer = Payjp::Customer.create(
    #         email: current_user.email,
    #         card: params['payjp_token'],
    #         metadata: {user_id: current_user.id}
    #       )
    #     #   トークン化した情報をアプリのcardsテーブルに登録
    #       @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
          
    #       if @card.save
    #         redirect_to user_path(current_user.id)
    #       else
    #         redirect_to action: "show"
    #       end
    #   else
    #     # binding.pry
    #       flash.now[:danger] = '登録出来ませんでした'
    #       render :new
    #   end
    # end
        
    def show
      @card = Card.find_by(user_id: current_user.id)
      unless @card.blank?
        Payjp.api_key = ENV['PAYJP_SECRET_KEY']
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer_card = customer.cards.retrieve(@card.card_id)
        
        # カードブランド表示の準備
        @card_brand = @customer_card.brand
        case @card_brand
          when "Visa"
            @card_src = "VISA.png"
          when "MasterCard"
            @card_src = "MasterCard.png"
          when "JCB"
            @card_src = "JCB.png"
          when "American Express"
            @card_src = "AmericanExpress.png"
          when "Diners Club"
            @card_src = "DinersClub.png"
          when "Discover"
            @card_src = "Discover.png"
        end
        # 有効期限の記述
        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2, 3)
      end
    end
    
        # PayjpとCardデータベースを削除
    def destroy
       @card = Card.find_by(user_id: current_user.id)
       unless @card.blank?
          Payjp.api_key = ENV['PAYJP_SECRET_KEY']
          customer = Payjp::Customer.retrieve(@card.customer_id)
          customer.delete
          @card.delete
          unless @card.destroy
            redirect_to card_path(current_user.id), danger: "削除できませんでした"
          end
       end
    end
    
    # payjpとCardのデータベース作成
    def pay
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      if params['payjp_token'].blank?
          redirect_to action: "new"
      else
          customer = Payjp::Customer.create(
            card: params['payjp_token'],
            metadata: {user_id: current_user.id}
          )
          @card = Card.new(
            user_id: current_user.id,
            customer_id: customer.id,
            card_id: customer.default_card
          )  
          if @card.save
            redirect_to action: "show"
          else
            redirect_to action: "pay" 
          end
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<div class = "card-new-wrapper">
    <div class = "container">
        <div class = "row">
            <div class = "col-md-offset-3 col-md-6">
                <h1 class = "text-center">クレジットカード登録</h1>
                <hr class = "hr-color">
                <% if @card.present? %>
                    <h3 class = "text-center">既に登録されています</h3>
                <% else %>
                <div class = "card-new">
                    <div class = "form-group">
                        <h4 class = "card-new-number-tag">カード番号</h4>
                        <div id = "number-form", class = "payjs-outer"></div>
                        <div class = "card-image">
                            <%= image_tag 'cards/VISA.png' %>
                            <%= image_tag 'cards/MasterCard.png' %>
                            <%= image_tag 'cards/JCB.png' %>
                            <%= image_tag 'cards/AmericanExpress.png' %>
                            <%= image_tag 'cards/DinersClub.png' %>
                            <%= image_tag 'cards/Discover.png' %>
                        </div>
                        <h4 class = "card-new-exp-tag">有効期限</h4>
                        <div id = "expiry-form", class = "payjs-outer"></div>
                        <h4 class = "card-new-cvc-tag">セキュリティーコード</h4>
                        <div id = "cvc-form", class = "payjs-outer"></div>
                    </div>
                </div>
                <div class = "form-group">
                    <%= form_with url: pay_cards_path,method: :post, id: "card_form" do |f| %>
                    <div id = "card_token">
                        <%= f.submit "登録する", class: "btn btn-outline-secondary btn-black", id: "info-submit" %>
                    </div>
                    <% end %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/cards/show.html.erb
<div class = "card-show-wrapper">
    <div class = "container">
        <div class = "row">
            <div class = "col-md-offset-3 col-md-6">
                <div class = "card-show">
                    <h1 class = "text-center">
                        登録クレジットカード情報
                    </h1>
                    <hr class = "hr-color">
                    <div class = "card-info">
                    <% if @customer_card.blank? %>
                        <h3 class = "card-show-noncard-tag">クレジットカードが登録されていません</h3>
                    <% else %>
                        <div class = "card-image">
                            <%= image_tag "cards/#{@card_src}" %>
                        </div>
                        <div class = "card-info-content">
                            <%= "**** **** **** " + @customer_card.last4 %>
                            <h4>有効期限</h4>
                            <%= @exp_month + " / " + @exp_year %>
                        </div>
                    </div>
                    <%= link_to card_path, method: :delete, class: 'btn btn-danger' do %>
                        削除する
                    <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>