config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'works/new'
  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  get 'lists/index'
  get 'rooms/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  
  resources :users
  resources :rooms do
      member do
        get "buy"
        post "pay"
    end
  end
  resources :messages
  resources :works do
    get 'works', to: 'works#search'
  end
  resources :password_resets, only: %i[new create edit update]
  
  namespace :admin do
    resources :users, only: [:index]
  end
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :costs, only: %i[new create]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
end

app/models/cost.rb
class Cost < ApplicationRecord
    VALID_COST_REGEX = /\A[0-9]+\z/
    validates :price, presence: true, format: {with: VALID_COST_REGEX}
    
    belongs_to :user
    belongs_to :room
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true, unless: :up_image
    
    belongs_to :user
    belongs_to :room, touch: true
    has_many :notifications,dependent: :destroy
    has_many_attached :images
    
    # def image
    #     self.images.variant(resize: '300×300').processed 
    # end
    private
    def up_image
        images.attached?
    end
end

app/models/message_image.rb
class MessageImage < ApplicationRecord
    belongs_to :message
    
    mount_uploader :photos, ImageUploader
end

app/models/notification.rb
class Notification < ApplicationRecord
    default_scope -> {order(created_at: :desc)}
    
    belongs_to :room, optional: true
    belongs_to :message, optional: true
    
    belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :entries, dependent: :destroy
    has_many :messages, dependent: :destroy
    has_many :users, through: :entries
    has_many :notifications, dependent: :destroy
    has_many :visitors, through: :notifications
    has_many :costs, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :work_type_relations,dependent: :destroy, foreign_key: 'type_id'
    has_many :works, through: :work_type_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
# def  has_unread_messages
#   #current_userのメッセージがある場合
#   unless self.rooms.room_ids.messages
# end  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])[a-z,A-Z,\d]{8,20}\z/
  
# 　allow_blankはエラーメッセージ用
  validates :name, 
            presence: true, length: {in: 1..15, allow_blank: true}
  validates :email,
            uniqueness: true, presence: true, format: {with: VALID_EMAIL_REGEX, allow_blank: true}
  validates :password, :password_confirmation, 
            presence: true, on: :create
  validates :password, :password_confirmation, 
            presence: true, on: :update, allow_blank: true, 
            format: {with: VALID_PASSWORD_REGEX, allow_blank: true}
  validates :password, confirmation: true
  validates :artist, presence: true
  validates :prefectures, presence: true
  # validates :profile_image, allow_blank: true
  validates :profile, length: {maximum: 200}, allow_blank: true
  validates :reset_password_token, allow_nil: true, uniqueness: true
  
  has_many :works, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :costs, dependent: :destroy
  has_one :card, dependent: :destroy
  
  mount_uploader :profile_image, ImageUploader
  
  enum artist: {yes: 1, no: 2}
  enum prefectures: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20, 岐阜県: 21, 静岡県: 22, 愛知県: 23,
    三重県: 24, 滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }
end

app/models/work.rb
class Work < ApplicationRecord
    validates :user_id, presence: true
    validates :image, presence: true
    validates :title, presence: true
    validates :description, presence: true
    validates :type_ids, presence: true
    
    belongs_to :user
    has_many :work_type_relations, dependent: :destroy
    has_many :types, through: :work_type_relations
    mount_uploader :image, ImageUploader
    
    # def save_works(savework_types)
    #     current_types = self.types.pluck(:work_type) unless self.types.nil?
    #     old_types = current_types - savework_types
    #     new_types = savework_types - current_types
        
    #     # 古いtypeを消去
    #     old_types.each do |old|
    #       self.types.delete Type.find_by(work_type: old) 
    #     end
        
    #     # typeを更新
    #     new_types.each do |new|
    #       new_work_type = Type.find_or_create_by(work_type: new)
    #       self.work_types << new_work_type
    #     end
    # end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
    # 最新メッセージのデータを取得して表示するメソッド
    def most_new_message_preview(room)
        #   最新メッセージのデータを取得する
        message = room.messages.order(created_at: :desc).limit(1)
        # 配列から取り出す
        message = message[0]
    end
    
    #相手のユーザー名を取得して表示するメソッド
    def opponent_user(room)
        # 中間テーブルから相手ユーザーのデータを取得
        entry = room.entries.where.not(user_id: current_user)
        # 相手ユーザーの名前を取得
        name = entry[0].user.name
        # 名前を表示
        # tag.p "#{name}", class: "dm_list_content_link_box_name"
    end
    
    # 長いメッセージは省略する
    def truncate_message(short)
      short = strip_tags(short).truncate(30) 
    end
    
    def unchecked_notifications
    #   @notifications =current_user.passive_notifications.where(checked: false) 
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cally</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- jQueryの読み込み -->
    <script src = "https://code.jquery.com/jquery-2.2.4.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Lightbox2の導入(画像ポップアップ機能)3行追加 -->
    <link href = "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel = "stylesheet">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type = "text/javascript"></script>
    
    <!-- google fontsの読み込み-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Shippori+Mincho&display=swap" rel="stylesheet">
    
    <!-- Pay.jp導入-->
    <script type = "text/javascript" src = "https://ja.pay.jp/"></script>
    <script src = "https://js.pay.jp/v2/pay.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class = "alart alert-<%= key %> flash-position" role = "alert">
        <%= value %>
      </div>
    <% end %>
    
    <nav class = "navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class = "container">
        <%= link_to "Cally", root_path, class: 'navbar-brand' %>

        <ul class = "nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <% if current_user.admin == true %>
                <%= link_to "管理者画面", admin_users_path, class: 'nav-text'%>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <% if current_user.profile_image.present? %>
                  <%= image_tag current_user.profile_image.url %>
                <% else %>
                  <%= image_tag "icons/マイページ.png" %>
                <% end %>
              <% end %>
            </li>
              <% if current_user.artist == "yes" %>
                <li>
                  <%= link_to new_work_path do %>
                    <%= image_tag "icons/投稿.png" %>
                  <% end %>
                </li>
              <% end %>
            <li>
              <%= link_to works_path do %>
                <%= image_tag "icons/作品一覧.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to rooms_path do %>
                <span class = "fa-stack fa-lg">
                  <%= image_tag "icons/メール.png", class: "nav-mail" %>
                  <% if checked_confirmation > 0 %>
                    <i class = "fa fa-circle nav-r-circle fa-stack-1x"></i>
                  <% end %>
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/ログアウト.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to "新規登録", new_user_path, class: "nav-text" %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/ログイン.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alart").fadeOut(5000);
      })
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class = "top-wrapper text-center">
    <div class = "container top-container">
        <h1 class = "text-white">Cally</h1>
        <h3 class = "text-white">それは、あなたに合った「書」を見つけるところ</h3>
        <div class = "row">
            <div class = "col-md-offset-3 col-md-6">
                <div class = "top-button-position">
                    <%= link_to '新規登録', new_user_path, class: 'btn btn-outline-secondary top-button-white' %>
                    <%= link_to 'ログイン', login_path, class: 'btn btn-outline-secondary top-button-white' %>
                </div>
            </div>
            
            <div class = "col-md-offset-3 col-md-6">
                <% if logged_in? %>
                    <%= link_to 'ログアウト', logout_path, method: :delete, class: 'text-white' %>
                <% end %>
            </div>
        </div>
    </div>
</div>